### ISSUE TITLE
Cross browser compatibility 

### ISSUE THREAD

**Issue by wesoudshoorn** [know-it-nl/know-it-nl.github.io#15]
Make sure the site works in more modern browsers.

**Comment by hanswesterbeek** [comment]
Waar schort het nu nog aan dan?

**Comment by wesoudshoorn** [comment]
Nog geen prefixing van CSS:

http://shouldiprefix.com/#flexbox

**Comment by wesoudshoorn** [comment]
Fixed with JS solution, prefixfree
